// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_shortCode_ from "./routes/[shortCode].ts";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_shorten from "./routes/api/shorten.ts";
import * as $api_urls from "./routes/api/urls.ts";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $stats_shortCode_ from "./routes/stats/[shortCode].tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DarkModeToggle from "./islands/DarkModeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[shortCode].ts": $_shortCode_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/shorten.ts": $api_shorten,
    "./routes/api/urls.ts": $api_urls,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/stats/[shortCode].tsx": $stats_shortCode_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/DarkModeToggle.tsx": $DarkModeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
